---
name: "OxiCleanarr Bridge"
guid: "a8c0f8e4-7d3c-4b5a-9e2f-1a2b3c4d5e6f"
version: "3.1.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "OxiClean for your media library - cleans up those tough symlink stains!"
description: "Jellyfin plugin for OxiCleanarr integration. Manages symlinks via HTTP API. The power of OxiClean, now for your media!"
category: "General"
owner: "ramonskie"
changelog: |
  Version 3.1.0 - Code Quality & Architecture Improvements
  - Implement dependency injection with IPluginServiceRegistrator
  - Add comprehensive code quality analyzers (StyleCop, SerilogAnalyzer, MultithreadingAnalyzer)
  - Create .editorconfig and jellyfin.ruleset for code standards
  - Add CI workflow for automated testing
  - Centralize version management with Directory.Build.props
  - Apply class-level admin authorization to all endpoints
  
  Version 3.0.0 - MAJOR REBRAND
  - Rebranded from Prunarr Bridge to OxiCleanarr Bridge
  - API endpoints changed: /api/prunarr/* → /api/oxicleanarr/*
  - All namespaces updated to Jellyfin.Plugin.OxiCleanarr
  - Billy Mays-themed configuration page
  - Same powerful symlink management features
  
  Version 2.0.0 - BREAKING CHANGES
  - Simplified to symlink-only design (Single Responsibility Principle)
  - Removed Virtual Folder management
  - Removed library scanning
  - Renamed endpoints: /leaving-soon/* → /symlinks/*
  - Removed /clear endpoint (use /remove for each item)
  - Added /symlinks/list endpoint
  - Removed AutoCreateVirtualFolder configuration
  - Removed VirtualFolderName configuration
artifacts:
  - "Jellyfin.Plugin.OxiCleanarr.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "net9.0"
