---
name: "Prunarr Bridge"
guid: "a8c0f8e4-7d3c-4b5a-9e2f-1a2b3c4d5e6f"
version: "1.0.3"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Bridge between Prunarr and Jellyfin for managing 'Leaving Soon' content"
description: "Jellyfin plugin for Prunarr integration. Manages 'Leaving Soon' virtual folders via HTTP API, allowing Prunarr to display media approaching deletion without direct filesystem access."
category: "General"
owner: "prunarr"
changelog: |
  Version 1.0.3
  - Updated to .NET 9.0 and Jellyfin 10.11.2
  - Automated manifest updates with JPRM
artifacts:
  - "Jellyfin.Plugin.PrunarrBridge.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "net9.0"
